//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ying.BookShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_bookinfo
    {
        public int BookId { get; set; }
        public int BookTypeId { get; set; }
        public string BookName { get; set; }
        public string BookType { get; set; }
        public string BookPress { get; set; }
        public System.DateTime BookPubDate { get; set; }
        public byte[] BookSize { get; set; }
        public string BookVersion { get; set; }
        public string BookAuthor { get; set; }
        public string BookTanslor { get; set; }
        public string Bookisbn { get; set; }
        public decimal BookPrice { get; set; }
        public int BookPages { get; set; }
        public string BookOutline { get; set; }
        public string BookCatalog { get; set; }
        public decimal BookMprice { get; set; }
        public decimal BookPrprice { get; set; }
        public int BookDealmount { get; set; }
        public Nullable<int> BookLookmount { get; set; }
        public string BookDiscount { get; set; }
        public decimal BookPic { get; set; }
        public int BookStoremount { get; set; }
        public System.DateTime BookStoretime { get; set; }
        public string BookPackstyle { get; set; }
    }
}
