//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ying.BookShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_customerinfo
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPwd { get; set; }
        public string Customertruename { get; set; }
        public string CustomerSex { get; set; }
        public string CustomerTel { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerAddr { get; set; }
        public System.DateTime CustomerRegTime { get; set; }
        public string CustomerQues { get; set; }
        public string CustomerAnswer { get; set; }
        public int CustomerLogTime { get; set; }
        public System.DateTime CustomerLastLogT { get; set; }
    }
}
