//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ying.BookShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order
    {
        public int Id { get; set; }
        public string OrderId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime Orderdate { get; set; }
        public int Ordermount { get; set; }
        public string message { get; set; }
        public string postmethod { get; set; }
        public string paymethod { get; set; }
        public string recevername { get; set; }
        public string receveraddr { get; set; }
        public string recevertel { get; set; }
        public string memo { get; set; }
        public decimal totalprice { get; set; }
    }
}
