//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ying.BookShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_parameter
    {
        public string webname { get; set; }
        public string regtiaoyue { get; set; }
        public string notice { get; set; }
        public string address { get; set; }
        public string postcode { get; set; }
        public string tel { get; set; }
        public string copyright { get; set; }
        public string weblogo { get; set; }
        public string website { get; set; }
        public string affordmethod { get; set; }
        public string shopstream { get; set; }
        public string postmethod { get; set; }
        public decimal postprice { get; set; }
        public string Postdescp { get; set; }
        public string worktime { get; set; }
        public string service { get; set; }
        public string law { get; set; }
        public string commques { get; set; }
        public string dealrule { get; set; }
    }
}
