//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ying.BookShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_reply
    {
        public int ReplyId { get; set; }
        public int CustomerId { get; set; }
        public string ReplyType { get; set; }
        public string Replytitle { get; set; }
        public string Replycontent { get; set; }
        public string Customername { get; set; }
        public System.DateTime Commentdate { get; set; }
        public string CustomerIP { get; set; }
    }
}
